before_build:
  - nuget restore

image: Visual Studio 2017

build:
  project: DebtRatchet.sln

test:
  assemblies:
    - '**\AttributeUpdater.Test\bin\Debug\AttributeUpdater.Test.dll'
    - '**\DebtRatchet.Test\bin\Debug\DebtRatchet.Test.dll'